### ISSUE TITLE
Swap out astro-imagetools with something else?

### ISSUE THREAD

**Issue by simkimsia** [ixartz/Astro-boilerplate#18]
Hi there, 

I notice that one of your dependencies is `astro-imagetools`

https://github.com/RafidMuhymin/astro-imagetools

and it uses an old version of `file-type` that has a CVE.

I have sent a PR to `astro-imagetools` but I doubt they will merge it.

https://github.com/RafidMuhymin/astro-imagetools/pull/181

Would you consider swapping it out for something that's more up to date?

**Comment by ixartz** [comment]
Hi @simkimsia,

Thank you so much for sharing this issue.

In this project, all the pages are generated in build time and everything is static.
I didn't take the time to investigate about the CVE, but most of the time, the template should be safe from the CVE because there isn't any server involve in production.

**Comment by ixartz** [comment]
I'm also more focus on Next.js framework, this is why I will take a little more time to make the swap
